---
- name: generate wireguard client config
  ansible.builtin.template:
    src: "etc/wireguard/client.conf.j2"
    dest: "/etc/wireguard/wireguard.conf"
    owner: "root"
    group: "root"
    mode: "0640"
  notify: restart wireguard
