---
- name: install-CentOS-7 | Install wireguard packages
  ansible.builtin.package:
    name:
      - "yum-plugin-elrepo"
    state: present

- name: install-CentOS-7 | Include RedHat/CentOS Steps
  ansible.builtin.include_tasks: "install-RedHat.yml"
