---
- name: install-Debian |  Install linux headers  (for Debian < 11)
  ansible.builtin.package:
    name:
      - "linux-headers-{{ wireguard_arch }}"
    state: present
  when:
    - ansible_distribution_major_version|int < 11

- name: install-Debian | Install Wireguard
  ansible.builtin.package:
    name:
      - "wireguard"
    state: present
