---
- name: wireguard-config | Ensure wireguard_path exists as directory
  ansible.builtin.file:
    path: "{{ wireguard_path }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0750"

- name: wireguard-config | Check wireguard private key
  ansible.builtin.stat:
    path: "{{ wireguard_path }}/privatekey"
  register: wg_stat_privatekey

- name: wireguard-config | Generate private key
  ansible.builtin.shell: "umask 077; wg genkey > {{ wireguard_path }}/privatekey"
  changed_when: false
  register: wireguard_private_key
  when:
    - not wg_stat_privatekey.stat.exists

- name: wireguard-config | Read wireguard private key
  ansible.builtin.slurp:
    src: "{{ wireguard_path }}/privatekey"
  register: wg_privatekey

- name: wireguard-config | Generate public key
  ansible.builtin.shell: "wg pubkey > {{ wireguard_path }}/publickey"
  changed_when: false
  args:
    stdin: "{{ wg_privatekey.content | b64decode | trim }}"
  when:
    - not wg_stat_privatekey.stat.exists

- name: wireguard-config | Read wireguard public key
  ansible.builtin.slurp:
    src: "{{ wireguard_path }}/publickey"
  register: wg_publickey
