---
- name: restart wireguard
  ansible.builtin.service:
    name: "wg-quick@wireguard"
    state: "{{ item }}"
  loop:
    - stopped
    - started
  when: (not wireguard_ignore_docker and
        ansible_virtualization_type != "docker" and
        ansible_virtualization_type != "containerd") or
        wireguard_ignore_docker | bool
