---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: Test if wireguard.conf exists
      ansible.builtin.lineinfile:
        name: '/etc/wireguard/wireguard.conf'
        line: '[interface]'
        state: present
      check_mode: true
      register: molecule_wireguard_conf
      failed_when: (molecule_wireguard_conf is changed) or (molecule_wireguard_conf is failed)

    - name: Check if wireguard is installed
      ansible.builtin.package:
        name: "wireguard"
        state: present
      register: wireguard_installed
      failed_when: (wireguard_installed is changed) or (wireguard_installed is failed)
      when:
        - ansible_os_family != "RedHat"

    - name: Check if wireguard-tools is installed
      ansible.builtin.package:
        name: "wireguard-tools"
        state: present
      register: wireguard_installed
      failed_when: (wireguard_installed is changed) or (wireguard_installed is failed)
      when: ansible_os_family == "RedHat"
